version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.17.3
    commands:
      - echo installing dependencies...
      - npm install
      - npm install -g @angular/cli@12.2.2
      - npm audit fix
  build:
    commands:
      - echo Build started...
      - ng build --configuration=$STAGE --aot --source-map=false --build-optimizer=false

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/'
  discard-paths: no
